#!/usr/bin/env bash
# launch_instance.sh — Launch one EC2 GPU instance from aws/config.env.
# Prerequisite: quota OK (check_quota.sh), KEY_NAME/SG_ID/AMI_ID set in config.env.
# Run: bash aws/launch_instance.sh
# Writes instance id + public IP to aws/instance.env

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../common/record.sh
source "${SCRIPT_DIR}/../common/record.sh"
start_recording "launch_instance" "${SCRIPT_DIR}/../records/aws"

# shellcheck source=config.env
source "${SCRIPT_DIR}/config.env"

INSTANCE_ENV="${SCRIPT_DIR}/instance.env"

for var in AMI_ID KEY_NAME SG_ID INSTANCE_TYPE; do
  if [[ -z "${!var}" ]] || [[ "${!var}" == *"xxxx"* ]] || [[ "${!var}" == "your-key-name" ]]; then
    echo "ERROR: Set ${var} in aws/config.env before launching."
    exit 1
  fi
done

if ! command -v aws &>/dev/null; then
  echo "ERROR: aws CLI not found."
  exit 1
fi

echo "Launching ${INSTANCE_TYPE} in ${AWS_REGION} ..."

RUN_ARGS=(
  --region "${AWS_REGION}"
  --image-id "${AMI_ID}"
  --instance-type "${INSTANCE_TYPE}"
  --key-name "${KEY_NAME}"
  --security-group-ids "${SG_ID}"
  --block-device-mappings "[{\"DeviceName\":\"/dev/sda1\",\"Ebs\":{\"VolumeSize\":${ROOT_VOLUME_GB},\"VolumeType\":\"gp3\",\"DeleteOnTermination\":true}}]"
  --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${INSTANCE_NAME_TAG}}]"
  --count 1
)

if [[ -n "${SUBNET_ID}" ]]; then
  RUN_ARGS+=(--subnet-id "${SUBNET_ID}")
fi

INSTANCE_ID="$(aws ec2 run-instances "${RUN_ARGS[@]}" --query 'Instances[0].InstanceId' --output text)"

echo "InstanceId: ${INSTANCE_ID}"
echo "Waiting for instance to be running ..."

aws ec2 wait instance-running --region "${AWS_REGION}" --instance-ids "${INSTANCE_ID}"
echo "Waiting for EC2 system and instance status checks ..."
aws ec2 wait instance-status-ok --region "${AWS_REGION}" --instance-ids "${INSTANCE_ID}"

PUBLIC_IP="$(aws ec2 describe-instances \
  --region "${AWS_REGION}" \
  --instance-ids "${INSTANCE_ID}" \
  --query 'Reservations[0].Instances[0].PublicIpAddress' \
  --output text)"

cat > "${INSTANCE_ENV}" <<EOF
# Generated by launch_instance.sh — do not commit secrets
export INSTANCE_ID="${INSTANCE_ID}"
export INSTANCE_PUBLIC_IP="${PUBLIC_IP}"
export AWS_REGION="${AWS_REGION}"
export INSTANCE_TYPE="${INSTANCE_TYPE}"
export INSTANCE_NAME_TAG="${INSTANCE_NAME_TAG}"
export AMI_ID="${AMI_ID}"
export KEY_NAME="${KEY_NAME}"
export SSH_USER="${SSH_USER}"
export SSH_KEY_PATH="${SSH_KEY_PATH}"
EOF

echo ""
echo "=== Launch complete ==="
echo "INSTANCE_ID=${INSTANCE_ID}"
echo "PUBLIC_IP=${PUBLIC_IP}"
echo "Saved to: ${INSTANCE_ENV}"
echo ""
echo "Next:"
echo "  1. source ${SCRIPT_DIR}/load_env.sh"
echo "  2. scp -r -i \${SSH_KEY_PATH} ${SCRIPT_DIR}/../phase2/remote ${SCRIPT_DIR}/../common \${SSH_USER}@\${INSTANCE_PUBLIC_IP}:~/"
echo "  3. bash ${SCRIPT_DIR}/ssh_tunnel.sh"
echo "  4. Follow phase2/RUNBOOK.md on the remote box."
